# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_user_todo_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='todo_items',
        ),
        migrations.RemoveField(
            model_name='user',
            name='todo_lists',
        ),
    ]
