# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171227_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(help_text='Enter a brief description of the task', max_length=1000, null=True),
        ),
    ]
