# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_todoitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='users',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
