# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_todoitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='dummy_attrib',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='users',
            field=models.ManyToManyField(help_text='Share this list with another user...', to=settings.AUTH_USER_MODEL),
        ),
    ]
